### ISSUE TITLE
sqlalchemy.exc.OperationalError: (OperationalError) FATAL:  role "ode" does not exist

### ISSUE THREAD

**Issue by arthurzenika** [makinacorpus/ODE#4]
```
make develop
[snip]
Installed /home/arthur/local/ODE
Processing dependencies for ode==0.0
Finished processing dependencies for ode==0.0
initialize_ode_db development.ini
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/ode/bin/initialize_ode_db", line 9, in <module>
    load_entry_point('ode==0.0', 'console_scripts', 'initialize_ode_db')()
  File "/home/arthur/local/ODE/ode/scripts/initializedb.py", line 32, in main
    Base.metadata.create_all(engine)
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3291, in create_all
    tables=tables)
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1546, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1539, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1729, in contextual_connect
    self.pool.connect(),
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 332, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 626, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 433, in checkout
    rec = pool._do_get()
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 945, in _do_get
    return self._create_connection()
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 278, in _create_connection
    return _ConnectionRecord(self)
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 404, in __init__
    self.connection = self.__connect()
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 527, in __connect
    connection = self.__pool._creator()
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 95, in connect
    connection_invalidated=invalidated
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 185, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 89, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 376, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/arthur/.virtualenvs/ode/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (OperationalError) FATAL:  role "ode" does not exist
 None None
make: *** [develop] Error 1
```

I guess one has to create a role in a database, but shouldn't that be in a different step ?

**Comment by isaacchansky** [comment]
Seems to be assumed in the that you have an "ode" user and an "ode" db before running `make develop`. Perhaps a note should be included in the documentation.
